# Generated by Django 3.0 on 2022-07-15 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tagline', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.IntegerField()),
                ('password', models.CharField(max_length=8)),
                ('image', models.ImageField(upload_to='signup_image')),
                ('address', models.TextField(default='', max_length=50)),
                ('bussiness_type', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='vprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('bussiness_type', models.CharField(max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('m_no', models.IntegerField()),
                ('address', models.TextField(max_length=50)),
                ('image', models.ImageField(upload_to='vimage')),
                ('up', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Signup')),
            ],
        ),
        migrations.CreateModel(
            name='Product_view',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='product_view')),
                ('dec', models.TextField(max_length=50)),
                ('price', models.IntegerField(default='')),
                ('rating', models.FloatField(default='')),
                ('up', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Signup')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('numbers', models.IntegerField(default='')),
                ('password', models.CharField(default='', max_length=8)),
                ('up', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Signup')),
            ],
        ),
        migrations.CreateModel(
            name='oContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('number', models.IntegerField()),
                ('problem', models.CharField(max_length=300)),
                ('bussiness_type', models.CharField(max_length=20)),
                ('up', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Signup')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('body_text', models.TextField()),
                ('pub_date', models.DateField()),
                ('mod_date', models.DateField()),
                ('number_of_comments', models.IntegerField()),
                ('number_of_pingbacks', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('authors', models.ManyToManyField(to='app1.Author')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Blog')),
            ],
        ),
    ]
